apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-argocd

spec:
  replicas: 2

  selector:
    matchLabels:
      app: demo-argocd

  template:
    metadata:
      labels:
        app: demo-argocd

    spec:
      containers:
      - name: httpd
        image: httpd:2.4

        ports:
        - containerPort: 80

        volumeMounts:
        - name: html-volume
          mountPath: /usr/local/apache2/htdocs/index.html
          subPath: index.html

      volumes:
      - name: html-volume
        configMap:
          name: demo-html
